apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jmeter
  name: podname
spec:
  containers:
  - image: imagename
    name: jmeter
    command: ["sh","-c","jmeter -n -t jmeter.jmx -l data.csv -q test.properties"]
  restartPolicy: Never
status: {}
